apply plugin: 'com.android.application'

android {
    namespace 'com.android.inputmethod.latin'
    compileSdkVersion 34

    // Required if using classes in android.test.runner
    useLibrary 'android.test.runner'

    // Required if using classes in android.test.base
    useLibrary 'android.test.base'

    // Required if using classes in android.test.mock
    useLibrary 'android.test.mock'

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 34
        versionName "1.0"

        applicationId 'com.android.inputmethod.latin'
        testApplicationId 'com.android.inputmethod.latin.tests'
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = false

        signingConfig signingConfigs.debug

        externalNativeBuild {
            cmake {
                cppFlags "-std=c++17"
            }
        }
    }

    signingConfigs {
        debug {
            storeFile file("../java/shared.keystore")
        }
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            proguardFiles getDefaultProguardFile('proguard-android.txt'), '../java/proguard.flags'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    flavorDimensions "default"

    sourceSets {
        main {
            res.srcDirs = ['../java/res']
            java.srcDirs = ['../common/src', '../java/src']
            manifest.srcFile '../java/AndroidManifest.xml'
        }

        androidTest {
            res.srcDirs = ['../tests/res']
            java.srcDirs = ['../tests/src']
            manifest.srcFile "../tests/AndroidManifest.xml"
        }
    }

    lintOptions {
        checkReleaseBuilds false
    }

    aaptOptions {
        noCompress 'dict', 'dat'
    }

    externalNativeBuild {
        cmake {
            path '../native/jni/CMakeLists.txt'
        }
    }
}

dependencies {
    implementation 'androidx.core:core:1.13.1'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'com.google.code.findbugs:jsr305:3.0.2'
    implementation project(':keyboard')

    testImplementation 'junit:junit:4.12'
    androidTestImplementation "org.mockito:mockito-core:1.9.5"
    androidTestImplementation 'com.google.dexmaker:dexmaker:1.2'
    androidTestImplementation 'com.google.dexmaker:dexmaker-mockito:1.2'
    androidTestImplementation 'androidx.test:runner:1.5.2'
    androidTestImplementation 'androidx.test:rules:1.5.0'
    androidTestImplementation 'androidx.test.uiautomator:uiautomator:2.2.0'
    androidTestImplementation 'androidx.annotation:annotation:1.7.1'
}
